### ISSUE TITLE
Could not translate host name "db" to address: Unknown host

### ISSUE THREAD

**Issue by vstankatz** [epicodus-lessons/ruby-rails-docker-container#1]
One students computer setup was unable to work with the provided docker template. The project compiled properly and they were able to make the database but once they entered rails console or tried to access the database for CRUD functionality they received this error: `PG::ConnectionBad (could not translate host name "db" to address: Unknown host)`. After debugging and googling we found the solution was to update the **docker-compose.yaml** file.

This is what the file currently looks like:
```docker-compose.yaml
  db:
    image: postgres:12.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
```
To work this needed to have the `environment` variable changed to instead have no postgres password and force the connection to be trusted. So instead the `db` section has to look like this:
```docker-compose.yaml
  db:
    image: postgres:12.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
```
This is definitely not the safest method for running a project since it means there is no password protection but it was the only solution we could find after 2 hours of bug diving. I'm not sure if this should be listed as a suggestion for students who have the error in the future or kept somewhere for teachers to note so its only used in severe circumstances.

**Comment by kullb3rg** [comment]
Closing this issue after transferring it to `epicodus-classroom/ruby-curriculum` for discussion and tracking there.
